### ISSUE TITLE
Licence for this controller

### ISSUE THREAD

**Issue by domiSchenk** [Shinjingi/Unity2D-Platform-Character-Controller#4]
Hey @Shinjingi

What is the license for this controller? can it be used in a game jam or even a commercial game?

thanks

**Comment by Shinjingi** [comment]
Hi Dominik,

you can use this controller in your projects without any worries, the only thing i ask is to mention me. 

Best regards,
Shinjingi
--
Inviato da Libero Mail

**Comment by domiSchenk** [comment]
thanks i will do that!
